In [2]:
library(readr)
library(dplyr)
source("../../Common/func.R")

In [11]:
# Read CSV file
FRG <- read_csv("../../../data/NaturalGas_WHG.csv", show_col_types = FALSE)
# Summary of the data
glimpse(FRG)

Rows: 1,051,200
Columns: 4
$ unix_ts   <dbl> 1333263600, 1333263660, 1333263720, 1333263780, 1333263840, …
$ counter   <dbl> 559900, 559900, 559900, 559900, 559900, 559900, 559900, 5599…
$ avg_rate  <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ inst_rate <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …

In [12]:
# Convert unix timestamp (int) column to readable/usable columns
FRG <- convert_timeStamp(FRG, "unix_ts") %>%
    mutate(avg_rate_modif = avg_rate / 60)

In [21]:
# Compute the average yearly consumption of natural gas (meter squared)
FRG_Total_Consumption <- yearly_consumption(FRG, "avg_rate_modif")
# Display the result
FRG_Total_Consumption %>%
    mutate(JG = yearly_consumption_v2 * 0.0373)

  nDays total_consumption yearly_consumption_v1 yearly_consumption_v2 JG
1 731   2469.175          1232.899              1234.588              46.05011

In [15]:
# Read CSV file
bill <- read_csv("../../../data/NaturalGas_Billing.csv", show_col_types = FALSE)
bill %>%
    summarise(
        totalJG = sum(`Billed GJ`) / 2
    )

  totalJG
1 51.15

In [19]:
# Read CSV file
monthly <- read_csv("../../../data/NaturalGas_Monthly.csv", show_col_types = FALSE)
monthly %>%
    summarise(
        totalJG = sum(`Net Consumption (GJ)`) / 2
    )

  totalJG
1 48.75