In [2]:
library(dplyr)
library(readr)
library(lubridate)

In [40]:
raw1 <- read_csv("../../data/Electricity_B1E.csv", show_col_types = FALSE)
raw2 <- read_csv("../../data/Electricity_B2E.csv", show_col_types = FALSE)
raw3 <- read_csv("../../data/Electricity_BME.csv", show_col_types = FALSE)

In [41]:
B1E <- raw1 %>% 
    mutate(
        timeStamp   = as.POSIXct(unix_ts, origin = "1970-01-01 12:00:00"),
        date        = as.Date(format(as.POSIXct(unix_ts, origin = "1970-01-01 12:00:00"), format = "%Y-%m-%d"), format = "%Y-%m-%d"),
        year        = format(as.POSIXct(unix_ts, origin = "1970-01-01 12:00:00"), format = "%Y"),
        month       = format(as.POSIXct(unix_ts, origin = "1970-01-01 12:00:00"), format = "%m"),
        day         = format(as.POSIXct(unix_ts, origin = "1970-01-01 12:00:00"), format = "%d"),
        hour        = format(as.POSIXct(unix_ts, origin = "1970-01-01 12:00:00"), format = "%H"),
        minute      = format(as.POSIXct(unix_ts, origin = "1970-01-01 12:00:00"), format = "%M")
    ) %>%
    select(-unix_ts)

B2E <- raw2 %>% 
    mutate(
        timeStamp   = as.POSIXct(unix_ts, origin = "1970-01-01 12:00:00"),
        date        = as.Date(format(as.POSIXct(unix_ts, origin = "1970-01-01 12:00:00"), format = "%Y-%m-%d"), format = "%Y-%m-%d"),
        year        = format(as.POSIXct(unix_ts, origin = "1970-01-01 12:00:00"), format = "%Y"),
        month       = format(as.POSIXct(unix_ts, origin = "1970-01-01 12:00:00"), format = "%m"),
        day         = format(as.POSIXct(unix_ts, origin = "1970-01-01 12:00:00"), format = "%d"),
        hour        = format(as.POSIXct(unix_ts, origin = "1970-01-01 12:00:00"), format = "%H"),
        minute      = format(as.POSIXct(unix_ts, origin = "1970-01-01 12:00:00"), format = "%M")
    ) %>%
    select(-unix_ts)

BME <- raw3 %>% 
    mutate(
        timeStamp   = as.POSIXct(unix_ts, origin = "1970-01-01 12:00:00"),
        date        = as.Date(format(as.POSIXct(unix_ts, origin = "1970-01-01 12:00:00"), format = "%Y-%m-%d"), format = "%Y-%m-%d"),
        year        = format(as.POSIXct(unix_ts, origin = "1970-01-01 12:00:00"), format = "%Y"),
        month       = format(as.POSIXct(unix_ts, origin = "1970-01-01 12:00:00"), format = "%m"),
        day         = format(as.POSIXct(unix_ts, origin = "1970-01-01 12:00:00"), format = "%d"),
        hour        = format(as.POSIXct(unix_ts, origin = "1970-01-01 12:00:00"), format = "%H"),
        minute      = format(as.POSIXct(unix_ts, origin = "1970-01-01 12:00:00"), format = "%M")
    ) %>%
    select(-unix_ts)

In [26]:
B1E %>% 
    mutate(
        `RP (kW)` = (S * DPF) / 1000
    ) %>% 
    group_by(year) %>%
    summarise(
        kW_Total = sum(`RP (kW)`),
        St_Total = (max(St) - min(St)) / 1000
    ) %>%
    ungroup() %>%
    summarise(avgkWH = mean(St_Total))

  avgkWH
1 92.58067

In [39]:
B2E %>%
    group_by(year) %>%
    summarise(
        kW_Total = (max(St) - min(St)) / 1000
    )

  year kW_Total
1 2012 207.746
2 2013 505.941
3 2014  86.436

In [42]:
BME %>%
    group_by(year) %>%
    summarise(
        kW_Total = (max(St) - min(St)) / 1000
    )

  year kW_Total
1 2012 368.971
2 2013 720.277
3 2014  82.728